SSA transformations + Liveness adjustment
Flakebi/simpleC-ssa pull request #3
Opened 2019-02-02 16:13 UTC by denis631

2019-02-05 12:49 UTC, lacinoire approved these changes
Thanks for updating the reaching definitions 👍🏼
And for commenting out my debug printlns 😃 There are more now, but we can clean that up while preparing for the presentation 🙂

2019-02-05 12:49 UTC, lacinoire commented on analysis/analysis/ReachingDefinitionsAnalysis.java
> +    Set<Tupel<Variable, Long>> getStateRepresentation(State s) {
It looks like you could also call dataflowOf(s) anywhere you would use this method 🤔

Is there a good reason for it, other than nicer naming? (which is okay, but then not consistent in all our analysis classes 😐)

2019-02-05 12:49 UTC, lacinoire commented on analysis/analysis/ReachingDefinitionsAnalysis.java
> +    Set<Tupel<Variable, Long>> getStateRepresentation(State s) {
If it is only used it in the SSA Transformation, maybe `getReachingDefinitions` would be a more descriptive name 😃

2019-02-05 12:49 UTC, lacinoire commented on cfgstructure/src/petter/cfg/edges/Psi.java
> +public class Psi extends Transition {
Actually, the method they are using for SSA ist called "Phi" (φ) and not "Psi" (ψ) 😇

2019-02-05 12:49 UTC, lacinoire commented on cfgstructure/src/petter/cfg/edges/Psi.java
> +     * @param lhs    lefthandside of an AssignmentEdge is a variable
I think this comment is not up to date?

2019-02-06 12:59 UTC, Flakebi requested changes

2019-02-06 12:59 UTC, Flakebi commented on analysis/analysis/SSATransform.java
> +                    }
If I understand this right, you are searching for variables which are contained twice or more in the `variables` list.
Your implementation uses two nested for loops, which contain a `contains`, this makes it `O(n^3)` which is quite inefficient.
I guess you can bring it down to `O(n)` with `groupingBy` like in [this StackOverflow answer](https://stackoverflow.com/a/27206052) (while also making it easier to understand).

2019-02-06 12:59 UTC, Flakebi commented on analysis/analysis/SSATransform.java
> +    private void insertNOP(State s1, State s2) {
If you take the `Transition` directly as (the only) argument, you don’t have to search for it again 😉.

2019-02-07 16:18 UTC, bpoettinger requested changes

2019-02-07 16:18 UTC, bpoettinger commented on analysis/analysis/SSATransform.java
> +        procedure = cu.getProcedure("main");
Maybe pass the procedure directly.  Only handling the main-procedure is an aspect unrelated to this class.

2019-02-07 16:18 UTC, bpoettinger commented on analysis/analysis/SSATransform.java
> +public class SSATransform extends AbstractVisitor {
Is subclassing the visitor required?

2019-02-07 16:18 UTC, bpoettinger commented on cfgstructure/src/petter/cfg/edges/Psi.java
> +    private List<Expression> lhs;
An explicit representation/class for assignments should avoid errors/make it more obvious/ease usage. E.g. class PsiAssignment { Variable from, to; }

2019-02-07 16:18 UTC, bpoettinger commented on analysis/analysis/SSATransform.java
> +                            Variable newVar = new Variable(id, name, lhs.getType());
You must not allocate variable IDs arbitrarily as there are already some variables allocated by the parser. Please use the compiler's ID generator instead.

2019-02-08 00:05 UTC, Flakebi commented on analysis/analysis/SSATransform.java
> +                            Variable newVar = new Variable(id, name, lhs.getType());
I would be interested to know how you can get new ideas. As far as I remember from the last time I tried to do this, only the parser can generate new ids and the parser is not available anymore at this stage. :)

2019-02-08 06:32 UTC, bpoettinger commented on analysis/analysis/SSATransform.java
> +                            Variable newVar = new Variable(id, name, lhs.getType());
All variable constructions in the framework get the ID from the symbol table and it in turn uses the ID generator, whose provided IDs a globally unique. Small modifications in the framework are neccessary to make it available.

The issue with the arbitrary allocation is that the comiliation unit can be put in an inconsistent state, e.g. using variables that are stated by the compiliation unit as global variables, what in turn affects my analysis.

2019-02-12 14:46 UTC, Fayanzar commented on cfgstructure/src/petter/cfg/edges/Psi.java
> +public class Psi extends Transition {
![default](https://user-images.githubusercontent.com/5547068/52643461-5a59de80-2edd-11e9-8acc-f3c8816a69e0.png)

2019-02-12 14:46 UTC, Fayanzar commented on cfgstructure/src/petter/cfg/edges/Psi.java
> +     * @param lhs    lefthandside of an AssignmentEdge is a variable
Yep, will fix it this evening.

2019-02-12 14:47 UTC, Fayanzar commented on analysis/analysis/SSATransform.java
> +public class SSATransform extends AbstractVisitor {
No, I was gonna use it at the very beginning but then realized I didn't need it. Will fix it this evening.

2019-02-16 09:42 UTC, Fayanzar commented on cfgstructure/src/petter/cfg/edges/Psi.java
> +    private List<Expression> lhs;
Yeah, it would make it easier, but it is used in such a way in lots of places for now, so I don't think rewriting will make much sense.

2019-02-16 09:44 UTC, Fayanzar commented on analysis/analysis/SSATransform.java
> +                            Variable newVar = new Variable(id, name, lhs.getType());
As for this one, I ask you to make these modifications on your own since I don't really know specific things in your analysis it might affect, therefore you'll make it obvoiusly better than me.

2019-02-16 12:27 UTC, merged