Redundancy Elimination
Flakebi/simpleC-ssa pull request #5
Opened 2019-03-04 11:57 UTC by Flakebi

Add redundancy elimination analyses and transformations.
Also add an ant build file to build our project with ant.

2019-03-05 18:24 UTC, bpoettinger requested changes
I think the avaiable expressions analysis misses a `lub` in the state visitor. The `lub` on the edges should be unnecessary, but should not affect the correctness. The other stuff seems OK.

2019-03-05 18:24 UTC, bpoettinger commented on analysis/analysis/redundancyelimination/AvailableExpressionAnalysis.java
> +            newSet = lub(newSet, old);
The `lub` above should not be necessary due to the monotonicity of the edge effects and the lack of joins on edges? Joins only occur on states.

Storing the values on edges is generally not required as we consider values at states and the framework cares about propagation of the value the destination states?

2019-03-05 18:24 UTC, bpoettinger commented on analysis/analysis/redundancyelimination/AvailableExpressionAnalysis.java
> +        if (d != null) {
I think you are missing joins here. As far as I remember for each change of a value of an incoming edge this method is called once. Without joining the old and the new value you omit the effect of other incoming edges.

2019-03-05 18:24 UTC, bpoettinger commented on analysis/analysis/redundancyelimination/AvailableExpressionAnalysis.java
> +        if (d != null) {
The other analysis contains the `lub` here.

2019-03-06 11:59 UTC, Flakebi commented on analysis/analysis/redundancyelimination/AvailableExpressionAnalysis.java
> +        if (d != null) {
Good catch, thanks!

2019-03-07 09:32 UTC, merged